### ISSUE TITLE
Vouchers don't work?

### ISSUE THREAD

**Issue by Kaludii** [VoltageMC/Super-Vouchers#1]
Hi, whenever I right-click, the voucher disapears but I'm not able to use the command like if I use a /nick voucher, it'll say redeemed /nick but I won't be able to use it

**Comment by pleasepoggitwork** [comment]
What version are you using, and do you have EssentialsPE installed?

**Comment by Kaludii** [comment]
I was using the latest version, build #6, and I do have EssentialsPE and I did use your version. Would it be a permissions issue? Like if I redeem a voucher, the command for the voucher doesnt even exist

**Comment by Kaludii** [comment]
Update: Installed another EssentialsPE and now it works, thanks!
